version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10
    labels: [dependencies, backend]
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    labels: [dependencies, docker]
    commit-message:
      prefix: deps
    ignore:
      - dependency-name: eclipse-temurin
        update-types: [version-update:semver-major]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10
    labels: [dependencies, ci]
    commit-message:
      prefix: ci
