version: 2
updates:
  - package-ecosystem: gradle
    directory: /dreamapp-devsecops-hardened-main/sleep-analysis-dreamapp-api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: /dreamapp-devsecops-hardened-main/WereableApp
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /dreamapp-devsecops-hardened-main/sleep-functions/functions
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /dreamapp-devsecops-hardened-main/dreamapp-web
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City

  - package-ecosystem: docker
    directory: /dreamapp-devsecops-hardened-main/sleep-analysis-dreamapp-api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
